version: '3.8'

services:
  db:
    container_name: 'db'
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

#  backend:
#    container_name: 'backend'
#    restart: always
#    depends_on:
#      - db
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    networks:
#      - mynetwork

networks:
  mynetwork:
